<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<title> <?php echo $page_title; ?> </title>
		<link rel="stylesheet" href="<?php echo $project_index; ?>/templates/assets/bootstrap/css/bootstrap.css">

		<script src="<?php echo $project_index; ?>/templates/assets/bootstrap/js/jquery.js"></script>
		<script src="<?php echo $project_index; ?>/templates/assets/bootstrap/js/bootstrap.js"></script>

	</head>
	<body>
		<div class="container">
			<!-- Topo -->
			<header class="row navbar navbar-inverse">
				<!-- Logo -->
				<div class="col-lg-6">

				</div>

				<!-- Perfil -->
				<div class="col-lg-6 text-right">
					
						<?php require $project_path.'/templates/navbar.phtml'; ?>
					
				</div>
			</header>


			<!-- Conteudo e o sidebar -->
			<section class="row">
				<!-- sidebar -->
				<div class="col-lg-3">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">
							<span class="glyphicon glyphicon-cog"></span>
							<strong>Área do Usuário</strong>
							</h3>
						</div>
						<div class="panel-body">
						<?php 
						if(isset($user)){
							require $project_path.'/templates/menu.phtml';
						}else{
							require $project_path.'/templates/forms/login.phtml';
						} 
						?>
						</div>
					</div>
				</div>

				<!-- conteudo -->
				<div class="col-lg-9">
					<div class="panel panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title">
								<span class="glyphicon glyphicon-th"></span>
								<strong> Painel de Controle </strong>
							</h3>
						</div>

						<div class="panel-body">
							<?php
								page_content();
							?>
						</div>
					</div>
				

				</div>
			</section>
		</div>

				
	</body>
</html>